### ISSUE TITLE
Unknown or missing state

### ISSUE THREAD

**Issue by psaintemarie** [birkirb/hue-cli#3]
Hi,

Using hue-cli with Hue Lux bulbs.

When getting light state, i get a "Unknown or missing state" message like this:

> hue light 1
1.  Salon: ON
    Brightness: 100 (39%)
Unknown or missing state: {"on"=>true, "bri"=>100, "alert"=>"none", "effect"=>"none", "reachable"=>true}

I guess this is because there are Hue Lux without colors.

Just FYI if you want to "fix" this. Otherwise, it's working fine.

**Comment by jaxxstorm** [comment]
I figured out this problem, and put a hacky thing together to fix it in a fork. If this project is still active, I'll submit it back. Think there's probably a better way to do it though.

**Comment by birkirb** [comment]
I'll take a look if you make a pull request.

**Comment by birkirb** [comment]
Should be fixed.
