### ISSUE TITLE
Failed to read configuration file

### ISSUE THREAD

**Issue by ssshake** [birkirb/hue-cli#7]
I just installed this gem but when I run it I get the following. Do you know why?

$ hue

Failed to read configuration file
Cause: No such file or directory - /home/rich/.hue-cli/applications.yml

**Comment by birkirb** [comment]
Try to start with:

```
hue register
```

**Comment by x4e** [comment]
It won't help. I have the same issue and the logged response returns:
`I, [2016-06-21T20:35:03.802407 #4617]  INFO -- : Found bridge (192.168.178.21:1900) with uuid: 2f402f80-da50-11e1-9b23-00178821ab7c
I, [2016-06-21T20:35:05.577092 #4617]  INFO -- : UDPSocket timed out.
I, [2016-06-21T20:35:05.579458 #4617]  INFO -- : Sending {"username":"386022600cc7a6d4af9390af19e06369","devicetype":"hue-cli"} to http://192.168.178.21/api
I, [2016-06-21T20:35:05.592671 #4617]  INFO -- : Response 200 OK: [{"error"=>{"type"=>6, "address"=>"/username", "description"=>"parameter, username, not available"}}]
`
The username is deprecated and shouldn't be part of the request anymore. See:
https://github.com/Veraticus/huey/pull/24/commits/a479992e13ed064dbefcafc979e3b6ee38ed4150

**Comment by ssshake** [comment]
i found that creating an empty file got around this but now I'm getting this. 

`rich@Linuxbox:~$ hue
Application not registered.
Found bridges:
  http://10.0.0.149/api (uuid: 2f402f80-da50-11e1-9b23-00178824a4b8)

Please type 'hue register' to register your application with the bridge.
rich@Linuxbox:~$ hue register
Please press the button on your bridge.
Once done, press Enter to continue with the registration.

Registering app...(b2a7381dc1c76a2ac61dba36e7781725)
parameter, username, not available
`

**Comment by x4e** [comment]
The registering is broken in hue-lib. I used the Python Library Phue and successfully requested a valid key. Afterwards updated the configuration file manually. Like this everything works fine.

**Comment by birkirb** [comment]
Yup, it's broken. I'll try and test on my bridge and fix it.

**Comment by ManuCart** [comment]
Any News? I'm blocked too

**Comment by birkirb** [comment]
Fixed.
